### ISSUE TITLE
Add a box to ask about the office hours

### ISSUE THREAD

**Issue by djavan-bertrand** [paug/cfp-devoxx#1]
Add a box in the proposal page to know if the speaker (would want to participate to a potential office hours. This means at least 1 hour of their time.

We could also add an "expertise field" with multiple answers allowed to be able to target the assets of the speaker. The answers might be: UI, UX, Architecture, Specific library, Kotlin...

**Comment by martinbonnin** [comment]
Checkbox added by https://github.com/paug/cfp-devoxx/commit/4cb2544b4e201767173bbcb61dc04d843a3773f8

Expertise field still TBD
