### ISSUE TITLE
"Kotlin - Crossplatform" tag should be renamed to "Kotlin - Multiplatform"

### ISSUE THREAD

**Issue by LouisCAD** [paug/cfp-devoxx#13]
BTW, if you look for https://kotl.in/crossplatform, you won't end up where you expected, being redirected to home, while https://kotl.in/multiplatform will welcome you with content, and here, there's no "crossplatform" mentioned. These don't have the same meaning. Kotlin doesn't cross the platforms, it compiles/integrated on multiple platforms, with specificities on each.

**Comment by martinbonnin** [comment]
Tag renamed
