### ISSUE TITLE
Saving a proposal as a draft always resets the presentation language to French

### ISSUE THREAD

**Issue by OussamaHaff** [paug/cfp-devoxx#19]
Steps to reproduce
- Create a proposal
- Select English as the language of presentation
- Save as a draft
- From the dashboard of proposals and submission, click on Edit proposal
- Always find the language of presentation set back to French

Env
- Safari Version 15.1 (16612.2.9.1.30, 16612)
- macOS BigSur 11.6.1
- Not reproduced on chromium based browser (Brave)

**Comment by eyal-lezmy** [comment]
The bug has been reproduced and fixed.
The fix has been deployed.
Thanks a lot @OussamaHaff !

**Comment by OussamaHaff** [comment]
Awesome ! 
All good now, thanks to you @eyal-lezmy : )
